BEGIN;

CREATE TABLE IF NOT EXISTS public.publisher
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS public.book
(
    isbn character varying(13),
    title character varying NOT NULL,
    publisher_id integer NOT NULL,
    PRIMARY KEY(isbn)
);

CREATE TABLE IF NOT EXISTS public.author
(
    id int GENERATED BY DEFAULT AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS public.book_author
(
    isbn character varying(13),
    author_id integer NOT NULL,
    PRIMARY KEY (isbn, author_id)
);

ALTER TABLE IF EXISTS public.book
    ADD FOREIGN KEY (publisher_id)
    REFERENCES public.publisher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.book_author
    ADD FOREIGN KEY (isbn)
    REFERENCES public.book (isbn) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.book_author
    ADD FOREIGN KEY (author_id)
    REFERENCES public.author (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE public.author 
    ADD CONSTRAINT uc_author_name UNIQUE (name);

ALTER TABLE public.publisher 
    ADD CONSTRAINT uc_publisher_name UNIQUE (name);

END;